<!-- EXPORT: TITULO -->
<div style="
background:#ffffff;
padding:35px;
border:3px solid #cbd5e1;
border-radius:15px;
margin:20px 0;
">

<h1 style="
font-size:55px;
color:#ef4444;
text-align:center;
margin-top:0;
margin-bottom:10px;
">
Caso de Negocio 3
</h1>

<h2 style="
font-size:35px;
color:#1f2937;
text-align:center;
font-weight:normal;
margin-top:0;
margin-bottom:25px;
">
Análisis de la Evolución de los Indicadores Monetarios y Financieros de Guatemala (2015–2025)
</h2>

<hr style="border:5px solid #cbd5e1; margin-bottom:30px;">
<hr style="border:3px solid #cbd5e1; margin-bottom:30px;">
<hr style="border:1px solid #cbd5e1; margin-bottom:30px;">

</div>

<div style="
background:#ffffff;
padding:35px;
border:3px solid #cbd5e1;
border-radius:15px;
margin:20px 0;
">


<h3 style="
font-size:35px;
color:#ef4444;
margin-bottom:10px;
">
Contexto del negocio
</h3>

<!-- EXPORT: CONTEXTO -->
<div style="
background:#ffffff;
padding:35px;
border:3px solid #cbd5e1;
border-radius:15px;
margin:20px 0;
">

<p style="
font-size:17px;
color:#374151;
line-height:1.8;
text-align:justify;
">
El Banco Central de Guatemala requiere monitorear la evolución de los principales indicadores monetarios y financieros para comprender el comportamiento de la liquidez, el crédito al sector privado, las remesas familiares y la actividad económica del país. El objetivo es generar información que apoye la toma de decisiones relacionadas con la estabilidad financiera y el seguimiento del crecimiento económico.
</p>



</div>

<div style="
background:#ffffff;
padding:35px;
border:3px solid #cbd5e1;
border-radius:15px;
margin:20px 0;
">


<h3 style="
font-size:35px;
color:#ef4444;
margin-bottom:10px;
">
Objetivo general
</h3>

<!-- EXPORT: OBJETIVO -->
<div style="
background:#ffffff;
padding:35px;
border:3px solid #cbd5e1;
border-radius:15px;
margin:20px 0;
">


<p style="
font-size:17px;
color:#374151;
line-height:1.8;
text-align:justify;
">
Analizar la evolución de los principales indicadores monetarios de Guatemala durante el período 2015–2025 para identificar tendencias, relaciones entre variables y posibles factores asociados al crecimiento económico y la liquidez del sistema financiero.
</p>

</div>

<div style="
background:#ffffff;
padding:30px;
border:3px solid #cbd5e1;
border-radius:15px;
margin:20px 0;
">

<h2 style="
font-size:35px;
color:#ef4444;
text-align:center;
margin-top:0;
margin-bottom:30px;
">
Preguntas de negocio
</h2>

<ol style="
font-size:17px;
color:#374151;
line-height:2;
padding-left:25px;
">

<li><b>¿Cómo evolucionaron los principales agregados monetarios durante el período?</b></li>

<li><b>¿Existe relación entre el crecimiento del PIB y el crédito bancario al sector privado?</b></li>

<li><b>¿Las remesas familiares presentan relación con el crecimiento de los medios de pago (M2)?</b></li>

<li><b>¿Cómo evolucionó el spread bancario en moneda nacional y moneda extranjera?</b></li>

<li><b>¿Qué indicador presentó el mayor crecimiento durante el período?</b></li>

<li><b>¿Cuál ha sido la variación trimestral del PIB?</b></li>

<li><b>¿Existe una relación entre el crecimiento de las remesas y el PIB?</b></li>

</ol>

</div>

In [2]:
# Librerias
import sys
sys.path.append("..")

import numpy as np
import pandas as pd

from math import pi
from bokeh.layouts import column
from bokeh.models import (
    ColumnDataSource,
    CustomJS,
    DatetimeTickFormatter,
    GlobalInlineStyleSheet,
    HoverTool,
    Label,
    Legend,
    LegendItem,
    NumeralTickFormatter,
    RangeTool,
    TapTool,
    LabelSet, 
    Span
)
from bokeh.plotting import figure, show, output_notebook
from bokeh.transform import dodge, factor_cmap

from utils import export_tables
from utils import export_charts
from utils import export_text

In [3]:
#Tema
output_notebook()

THEMES = {
    "economic_modern": {
        "BACKGROUND": "#faf7f5",
        "PANEL": "#ffffff",
        "GRID": "#d6d3d1",
        "GRID_ALPHA": 0.45,
        "BORDER": "#cbd5e1",
        "TEXT": "#1f2937",
        "TEXT_SOFT": "#64748b",
        "TEXT_SIZE": "10pt",
        "ACCENT": "#ef4444",
        "POSITIVE": "#22c55e",
        "NEGATIVE": "#dc2626",
        "WARNING": "#f59e0b",
        "COLORS": {
            "PIB": "#2563eb",         
            "NUMERARIO": "#f97316",   
            "CREDITO": "#16a34a",     
            "M2": "#9333ea",           
            "REMESAS": "#eab308",      
            "SPREAD_MN": "#dc2626",    
            "SPREAD_ME": "#06b6d4"     
        }
    }
}

theme = THEMES["economic_modern"]
colors = theme["COLORS"]

In [4]:
# Tables and Charts

TABLES = {}
CHARTS = {}

In [5]:
#Base de datos
df = pd.read_csv("../data/caso_3_lim.csv")
df.columns.name = None
TABLES["table"] = df
df

,Trimestre,Año,numerario en circulacion,credito bancario total al sector privado,medios de pagos totales,spread bancario en mn,spread bancario en me,remesas familiares,PIB Trimestral
0,1,2015,70278.3,465675.2,558854.6,8.03%,3.03%,10677.93,"117,897.3"
1,2,2015,71145.8,470759.0,564714.4,7.94%,3.02%,11991.96,"116,183.4"
2,3,2015,73002.3,475810.1,571462.5,7.83%,2.98%,12584.58,"118,716.5"
3,4,2015,73663.8,480657.7,574962.5,7.75%,2.95%,12949.65,"123,225.6"
4,1,2016,77432.8,518424.9,604368.3,7.59%,3.01%,12796.27,"123,838.5"
5,2,2016,77830.9,520442.7,611167.3,7.61%,3.03%,14215.73,"122,799.4"
6,3,2016,79324.2,523964.6,614850.4,7.65%,3.06%,13336.83,"124,518.0"
7,4,2016,83048.9,536542.8,628914.3,7.67%,3.10%,14168.37,"130,845.7"
8,1,2017,89216.9,544840.4,641288.3,7.61%,3.04%,14434.38,"131,682.7"
9,2,2017,90815.3,549986.5,656254.7,7.63%,3.02%,15522.05,"127,650.4"
10,3,2017,91484.1,551249.3,665484.7,7.64%,3.02%,14947.24,"130,291.7"
11,4,2017,95375.6,561622.8,679206.0,7.65%,3.03%,15405.75,"136,882.6"
12,1,2018,99364.6,566915.8,692491.8,7.78%,3.11%,14907.84,"136,945.1"
13,2,2018,97686.3,573378.7,705501.6,7.77%,3.12%,17751.23,"134,587.6"
14,3,2018,99746.4,579263.4,719265.9,7.76%,3.15%,18340.31,"136,449.4"
15,4,2018,107385.6,598683.6,738983.6,7.75%,3.19%,19058.12,"143,385.9"
16,1,2019,110022.4,606750.2,756806.4,7.73%,3.42%,17050.81,"144,940.7"
17,2,2019,111459.2,615318.7,770431.5,7.75%,3.45%,20929.46,"145,359.2"
18,3,2019,115678.4,617310.7,788696.5,7.72%,3.45%,21720.56,"147,623.6"
19,4,2019,124789.3,632550.3,812983.6,7.68%,3.42%,21349.42,"156,048.5"
20,1,2020,128518.0,646737.5,839986.0,7.81%,3.16%,18385.73,"151,214.2"
21,2,2020,138702.2,663936.7,876841.8,7.85%,3.15%,19220.53,"136,507.7"
22,3,2020,149306.0,657969.1,925433.6,7.88%,3.15%,24604.32,"150,128.8"
23,4,2020,158714.6,672521.1,970135.8,7.93%,3.14%,25609.39,"162,271.8"
24,1,2021,164650.9,682707.1,1004037.2,8.04%,3.42%,24344.50,"162,670.4"
25,2,2021,165612.5,698395.3,1027504.0,8.05%,3.41%,29654.79,"161,775.5"
26,3,2021,170488.6,718130.7,1050036.7,8.06%,3.41%,31344.30,"167,039.9"
27,4,2021,180156.3,749025.8,1078804.9,8.07%,3.41%,33205.39,"177,193.0"
28,1,2022,188493.9,775152.9,1124387.4,7.99%,3.04%,30368.50,"179,171.0"
29,2,2022,191889.4,804250.3,1145884.8,8.01%,2.98%,36806.44,"179,610.5"
30,3,2022,196033.2,834760.2,1172161.9,8.04%,2.97%,35869.92,"185,624.2"
31,4,2022,205177.2,876478.1,1204517.8,8.06%,2.95%,37146.69,"196,401.9"
32,1,2023,213535.3,897415.8,1239764.0,7.89%,3.28%,34774.84,"200,405.8"
33,2,2023,219051.4,923779.9,1266321.2,7.87%,3.30%,40936.44,"200,133.3"
34,3,2023,226073.9,954835.0,1288164.6,7.85%,3.31%,40298.04,"203,402.0"
35,4,2023,235883.3,998392.9,1295463.2,7.83%,3.30%,39478.06,"212,918.7"
36,1,2024,241648.7,1041338.4,1315673.2,7.55%,3.33%,36661.63,"214,009.8"
37,2,2024,241964.2,1071839.4,1334439.4,7.49%,3.29%,43530.99,"213,837.1"
38,3,2024,245878.3,1097745.9,1353332.8,7.44%,3.26%,43174.11,"219,785.4"
39,4,2024,254391.7,1127876.0,1387724.9,7.41%,3.24%,43908.46,"230,755.2"
40,1,2025,259548.0,1155665.2,1421946.5,7.60%,3.24%,43633.43,"230,802.6"
41,2,2025,268673.2,1185001.3,1465146.9,7.64%,3.24%,49964.11,"231,747.8"
42,3,2025,278106.6,1209891.4,1517531.7,7.66%,3.21%,52550.14,"235,583.1"
43,4,2025,290739.5,1223336.3,1573084.1,7.68%,3.21%,50366.69,"248,872.0"

<!-- EXPORT: PREGUNTA_1 -->
<div style="
background:#ffffff;
padding:30px;
border:3px solid #cbd5e1;
border-radius:15px;
margin:20px 0;
">

<ol style="
font-size:25px;
color:#374151;
line-height:1.5;
padding-left:25px;
">
    
<b>¿Cómo evolucionaron los principales agregados monetarios durante el período?</b>
</ol>

</div>

In [6]:
# Data Question 1

variable_ques1 = ["numerario en circulacion", "credito bancario total al sector privado", 
                  "medios de pagos totales", "remesas familiares", "PIB Trimestral"]
df_ques1 = df[["Año", "Trimestre"] + variable_ques1]
df_ques1["Periodo"] = (df_ques1["Año"].astype(str) + "-T"+ df_ques1["Trimestre"].astype(str))
df_ques1["Fecha"] = pd.to_datetime(df_ques1["Año"].astype(str) + "-" + ((df_ques1["Trimestre"] - 1) * 3 + 1).astype(str) + "-01")

for col in variable_ques1: 
    df[col] = (df[col].astype(str).str.replace(",", "", regex=False).astype(float))

for var in variable_ques1: 
    df_ques1[var] = df[var] / df[var].iloc[0] * 100

source = ColumnDataSource(df_ques1)
df_ques1.columns.name = None
TABLES["table_ques1"] = df_ques1
df_ques1

,Año,Trimestre,numerario en circulacion,credito bancario total al sector privado,medios de pagos totales,remesas familiares,PIB Trimestral,Periodo,Fecha
0,2015,1,100.000000,100.000000,100.000000,100.000000,100.000000,2015-T1,2015-01-01
1,2015,2,101.234378,101.091705,101.048537,112.306037,98.546277,2015-T2,2015-04-01
2,2015,3,103.876019,102.176388,102.256025,117.855989,100.694842,2015-T3,2015-07-01
3,2015,4,104.817276,103.217371,102.882306,121.274910,104.519442,2015-T4,2015-10-01
4,2016,1,110.180241,111.327573,108.144104,119.838489,105.039301,2016-T1,2016-01-01
5,2016,2,110.746703,111.760880,109.360700,133.131890,104.157941,2016-T2,2016-04-01
6,2016,3,112.871541,112.517179,110.019744,124.900894,105.615650,2016-T3,2016-07-01
7,2016,4,118.171470,115.218247,112.536302,132.688358,110.982779,2016-T4,2016-10-01
8,2017,1,126.948005,117.000089,114.750474,135.179571,111.692719,2017-T1,2017-01-01
9,2017,2,129.222392,118.105173,117.428523,145.365722,108.272539,2017-T2,2017-04-01
10,2017,3,130.174037,118.376349,119.080115,139.982562,110.512879,2017-T3,2017-07-01
11,2017,4,135.711308,120.603975,121.535369,144.276559,116.103253,2017-T4,2017-10-01
12,2018,1,141.387313,121.740604,123.912696,139.613577,116.156265,2018-T1,2018-01-01
13,2018,2,138.999236,123.128459,126.240636,166.242240,114.156643,2018-T2,2018-04-01
14,2018,3,141.930582,124.392151,128.703584,171.759039,115.735814,2018-T3,2018-07-01
15,2018,4,152.800509,128.562483,132.231818,178.481410,121.619325,2018-T4,2018-10-01
16,2019,1,156.552449,130.294720,135.420984,159.682729,122.938100,2019-T1,2019-01-01
17,2019,2,158.596893,132.134737,137.859025,196.006717,123.293069,2019-T2,2019-04-01
18,2019,3,164.600453,132.562503,141.127316,203.415456,125.213724,2019-T3,2019-07-01
19,2019,4,177.564483,135.835084,145.473187,199.939689,132.359689,2019-T4,2019-10-01
20,2020,1,182.870104,138.881671,150.304927,172.184403,128.259256,2020-T1,2020-01-01
21,2020,2,197.361348,142.575061,156.899809,180.002397,115.785264,2020-T2,2020-04-01
22,2020,3,212.449647,141.293567,165.594700,230.422189,127.338624,2020-T3,2020-07-01
23,2020,4,225.837278,144.418492,173.593597,239.834781,137.638267,2020-T4,2020-10-01
24,2021,1,234.284125,146.605853,179.659826,227.988945,137.976357,2021-T1,2021-01-01
25,2021,2,235.652399,149.974768,183.858914,277.720401,137.217307,2021-T2,2021-04-01
26,2021,3,242.590672,154.212786,187.890857,293.542850,141.682549,2021-T3,2021-07-01
27,2021,4,256.346981,160.847260,193.038565,310.972164,150.294366,2021-T4,2021-10-01
28,2022,1,268.210671,166.457844,201.194980,284.404374,151.972098,2022-T1,2022-01-01
29,2022,2,273.042177,172.706277,205.041669,344.696397,152.344880,2022-T2,2022-04-01
30,2022,3,278.938449,179.258032,209.743626,335.925783,157.445675,2022-T3,2022-07-01
31,2022,4,291.949578,188.216615,215.533307,347.882876,166.587276,2022-T4,2022-10-01
32,2023,1,303.842438,192.712818,221.840171,325.670238,169.983367,2023-T1,2023-01-01
33,2023,2,311.691376,198.374296,226.592248,383.374306,169.752234,2023-T2,2023-04-01
34,2023,3,321.683791,205.043129,230.500849,377.395619,172.524731,2023-T3,2023-07-01
35,2023,4,335.641727,214.396837,231.806842,369.716415,180.596757,2023-T4,2023-10-01
36,2024,1,343.845398,223.619037,235.423167,343.340235,181.522223,2024-T1,2024-01-01
37,2024,2,344.294327,230.168882,238.781143,407.672555,181.375740,2024-T2,2024-04-01
38,2024,3,349.863756,235.732094,242.161879,404.330334,186.421063,2024-T3,2024-07-01
39,2024,4,361.977595,242.202290,248.315913,411.207603,195.725602,2024-T4,2024-10-01
40,2025,1,369.314568,248.169797,254.439437,408.631916,195.765806,2025-T1,2025-01-01
41,2025,2,382.298946,254.469489,262.169605,467.919438,196.567521,2025-T2,2025-04-01
42,2025,3,395.721866,259.814437,271.543206,492.137896,199.820607,2025-T3,2025-07-01
43,2025,4,413.697400,262.701621,281.483610,471.689644,211.092196,2025-T4,2025-10-01

In [7]:
#Chart Question 1
p_ques1 = figure(
    width=950,
    height=450,
    x_axis_type="datetime",
    title="Evolución de los principales agregados monetarios (Base 100)",
    background_fill_color=theme["BACKGROUND"],
    border_fill_color=theme["PANEL"],
    tools="pan,wheel_zoom,box_zoom,reset,save"
)
p_ques1 .line(
    "Fecha",
    "numerario en circulacion",
    source=source,
    color=colors["NUMERARIO"],
    line_width=3,
    legend_label="Numerario"
)

p_ques1 .line(
    "Fecha",
    "credito bancario total al sector privado",
    source=source,
    color=colors["CREDITO"],
    line_width=3,
    legend_label="Crédito"
)

p_ques1 .line(
    "Fecha",
    "medios de pagos totales",
    source=source,
    color=colors["M2"],
    line_width=3,
    legend_label="M2"
)

p_ques1 .line(
    "Fecha",
    "remesas familiares",
    source=source,
    color=colors["REMESAS"],
    line_width=3,
    legend_label="Remesas"
)

p_ques1 .line(
    "Fecha",
    "PIB Trimestral",
    source=source,
    color=colors["PIB"],
    line_width=3,
    legend_label="PIB"
)

hover = HoverTool(
    tooltips="""
    <div style="
        background:#1f1720;
        border:1px solid #ff6b81;
        border-radius:8px;
        padding:8px;
        color:white;
    ">
        <b>Fecha:</b> @Periodo<br>
        <b>Valor:</b> $y{0.0}
    </div>
    """
)

p_ques1 .add_tools(hover)
p_ques1 .stylesheets = [
    GlobalInlineStyleSheet(css="""
    .bk-Tooltip {
        --tooltip-color: transparent !important;
        --tooltip-border: transparent !important;
    }
    .bk-tooltip-content {
        background: transparent !important;
        border: none !important;
        box-shadow: none !important;
        padding: 0 !important;
    }
    """)
]
p_ques1.legend.location = "top_left"
p_ques1.legend.orientation = "vertical"
p_ques1.legend.background_fill_color = theme["PANEL"]
p_ques1.legend.background_fill_alpha = 0.9
p_ques1.legend.border_line_color = theme["BORDER"]
p_ques1.legend.label_text_color = theme["TEXT"]
p_ques1.legend.label_text_font_size = "10pt"
p_ques1.legend.padding = 8
p_ques1.legend.spacing = 6
p_ques1.legend.margin = 5
p_ques1.legend.click_policy = "hide"
p_ques1.yaxis.formatter = NumeralTickFormatter(format="0.00a")
p_ques1.toolbar.logo = None
p_ques1.toolbar.autohide = True
p_ques1.title.text_color = theme["ACCENT"] 
p_ques1.title.text_font_size = "20pt"        
p_ques1.title.align = "center"  
p_ques1.yaxis.axis_label = 'Saldos'
p_ques1.yaxis.axis_label_text_color = theme["TEXT"]
p_ques1.xaxis.major_label_text_color = theme["TEXT_SOFT"]
p_ques1.yaxis.major_label_text_color = theme["TEXT_SOFT"]
p_ques1.outline_line_color = theme["BORDER"]
p_ques1.xgrid.grid_line_color = theme["GRID"]
p_ques1.ygrid.grid_line_color = theme["GRID"]
p_ques1.xgrid.grid_line_alpha = theme["GRID_ALPHA"]
p_ques1.ygrid.grid_line_alpha = theme["GRID_ALPHA"]

select = figure(
    title="Seleccionar período",
    height=120,
    width=950,
    x_axis_type="datetime",
    y_axis_type=None,
    tools="",
    toolbar_location=None,
    background_fill_color=theme["BACKGROUND"],
    border_fill_color=theme["PANEL"]
)
select.line("Fecha", "medios de pagos totales", source=source, color=colors["M2"])
range_tool = RangeTool(x_range=p_ques1.x_range)
range_tool.overlay.fill_color = theme["ACCENT"]
range_tool.overlay.fill_alpha = 0.25
select.add_tools(range_tool)

CHARTS["chart_ques1"] = column(p_ques1)
show(column(p_ques1, select))

<!-- EXPORT: ANALISIS_1 -->
<div style="
background:#ffffff;
padding:25px;
border-left:6px solid #cbd5e1;
border-radius:10px;
margin:20px 0;
color:#e0e0e0;        
">

<p style="
font-size:15px;
color:#374151;
line-height:1.5;
text-align:justify;
">
Durante el período comprendido entre 2015 y 2025, los principales agregados monetarios de Guatemala muestran una tendencia general de crecimiento sostenido. El Producto Interno Bruto (PIB) presenta la evolución más estable y moderada, reflejando un crecimiento económico constante a lo largo del período. Por su parte, los medios de pago (M2) y el crédito bancario al sector privado registran un crecimiento superior al del PIB, manteniendo igualmente una trayectoria estable y con baja volatilidad. Finalmente, el numerario en circulación y las remesas familiares son las variables que experimentan el mayor crecimiento relativo, aunque las remesas destacan por presentar fluctuaciones más pronunciadas durante algunos trimestres.
</p>

<p style="
font-size:15px;
color:#374151;
line-height:1.5;
text-align:justify;
">
Las diferencias en el comportamiento de estas variables pueden asociarse a su naturaleza económica. Mientras que el PIB, el crédito bancario, los medios de pago y el numerario en circulación responden principalmente a las condiciones macroeconómicas internas y a la política monetaria implementada por el Banco de Guatemala, las remesas familiares dependen en mayor medida de factores externos, como la situación económica de los países de origen de los migrantes, las condiciones del mercado laboral internacional y los cambios en las políticas migratorias. Esta dependencia explica la mayor volatilidad observada en dicha variable.
</p>

<p style="
font-size:15px;
color:#374151;
line-height:1.5;
text-align:justify;
">
Desde una perspectiva de política económica, los resultados evidencian que el seguimiento de las remesas familiares y del numerario en circulación resulta especialmente relevante debido a la magnitud de su crecimiento y a la influencia que ejercen sobre la liquidez de la economía. No obstante, el análisis de estos indicadores debe complementarse con variables como el crédito bancario, los medios de pago y el PIB, ya que en conjunto proporcionan una visión más completa de la evolución del sistema monetario y financiero del país y permiten fundamentar de mejor manera la toma de decisiones.
</p>


</div>

<!-- EXPORT: PREGUNTA_2 -->
<div style="
background:#ffffff;
padding:30px;
border:3px solid #cbd5e1;
border-radius:15px;
margin:20px 0;
">

<ol style="
font-size:25px;
color:#374151;
line-height:1.5;
padding-left:25px;
">
    
<b>¿Existe relación entre el crecimiento del PIB y el crédito bancario al sector privado?</b></ol>

</div>

In [8]:
# Data Question 2
df_ques2 = df[["Trimestre","Año","credito bancario total al sector privado", "PIB Trimestral"]]
df_ques2["Año"] = df_ques2["Año"].astype(str)
source = ColumnDataSource(df_ques2)
df_ques2.columns.name = None
TABLES["table_ques2"] = df_ques2
df_ques2

    Trimestre   Año  credito bancario total al sector privado  PIB Trimestral
0           1  2015                                  465675.2        117897.3
1           2  2015                                  470759.0        116183.4
2           3  2015                                  475810.1        118716.5
3           4  2015                                  480657.7        123225.6
4           1  2016                                  518424.9        123838.5
5           2  2016                                  520442.7        122799.4
6           3  2016                                  523964.6        124518.0
7           4  2016                                  536542.8        130845.7
8           1  2017                                  544840.4        131682.7
9           2  2017                                  549986.5        127650.4
10          3  2017                                  551249.3        130291.7
11          4  2017                                  561622.8        136882.6
12          1  2018                                  566915.8        136945.1
13          2  2018                                  573378.7        134587.6
14          3  2018                                  579263.4        136449.4
15          4  2018                                  598683.6        143385.9
16          1  2019                                  606750.2        144940.7
17          2  2019                                  615318.7        145359.2
18          3  2019                                  617310.7        147623.6
19          4  2019                                  632550.3        156048.5
20          1  2020                                  646737.5        151214.2
21          2  2020                                  663936.7        136507.7
22          3  2020                                  657969.1        150128.8
23          4  2020                                  672521.1        162271.8
24          1  2021                                  682707.1        162670.4
25          2  2021                                  698395.3        161775.5
26          3  2021                                  718130.7        167039.9
27          4  2021                                  749025.8        177193.0
28          1  2022                                  775152.9        179171.0
29          2  2022                                  804250.3        179610.5
30          3  2022                                  834760.2        185624.2
31          4  2022                                  876478.1        196401.9
32          1  2023                                  897415.8        200405.8
33          2  2023                                  923779.9        200133.3
34          3  2023                                  954835.0        203402.0
35          4  2023                                  998392.9        212918.7
36          1  2024                                 1041338.4        214009.8
37          2  2024                                 1071839.4        213837.1
38          3  2024                                 1097745.9        219785.4
39          4  2024                                 1127876.0        230755.2
40          1  2025                                 1155665.2        230802.6
41          2  2025                                 1185001.3        231747.8
42          3  2025                                 1209891.4        235583.1
43          4  2025                                 1223336.3        248872.0

In [9]:
# Chart Question 2

p_ques2 = figure(
    height=400, width=800,
    tools="pan,wheel_zoom,reset,save,tap",
    x_axis_label="Crédito Bancario",
    y_axis_label="PIB",
    background_fill_color=theme["BACKGROUND"],
    border_fill_color=theme["PANEL"],
    title="Relación Crédito Bancario - PIB"
)

renderer = p_ques2.scatter(
    x="credito bancario total al sector privado",
    y="PIB Trimestral",
    source=source,
    size=9,
    color=colors["CREDITO"],  
    alpha=0.8
)

hover = HoverTool(
    tooltips="""
    <div style="
        background:#0b0b0b;
        border:1px solid #d4af37;
        border-radius:6px;
        padding:8px;
        color:#fff;
    ">
        <div><b>Año:</b> @Año</div>
        <div><b>Trimestre:</b> @Trimestre</div>
        <div><b>Crédito Bancario:</b> @{credito bancario total al sector privado}{0,0.00}</div>
        <div><b>PIB:</b> @{PIB Trimestral}{0,0.00}</div>
    </div>
    """,
    renderers=[renderer]
)

p_ques2.add_tools(hover)
taptool = p_ques2.select(type=TapTool)
p_ques2.yaxis.formatter = NumeralTickFormatter(format="0.00a")
p_ques2.xaxis.formatter = NumeralTickFormatter(format="0.00a")
p_ques2.title.text_color = theme["ACCENT"] 
p_ques2.title.text_font_size = "20pt"        
p_ques2.title.align = "center"  
p_ques2.xaxis.axis_label_text_color = theme["TEXT"]
p_ques2.yaxis.axis_label_text_color = theme["TEXT"]
p_ques2.xaxis.major_label_text_color = theme["TEXT_SOFT"]
p_ques2.yaxis.major_label_text_color = theme["TEXT_SOFT"]
p_ques2.outline_line_color = theme["BORDER"]
p_ques2.xgrid.grid_line_color = theme["GRID"]
p_ques2.ygrid.grid_line_color = theme["GRID"]
p_ques2.xgrid.grid_line_alpha = theme["GRID_ALPHA"]
p_ques2.ygrid.grid_line_alpha = theme["GRID_ALPHA"]
p_ques2.toolbar.logo = None
p_ques2.toolbar.autohide = True

CHARTS["chart_ques2"] = p_ques2
show(p_ques2)

<!-- EXPORT: ANALISIS_2 -->
<div style="
background:#ffffff;
padding:25px;
border-left:6px solid #cbd5e1;
border-radius:10px;
margin:20px 0;
color:#e0e0e0;        
">

<p style="
font-size:15px;
color:#374151;
line-height:1.5;
text-align:justify;
">
El crédito bancario total al sector privado presenta una relación lineal positiva con el Producto Interno Bruto (PIB), evidenciando que conforme la economía ha crecido durante el período analizado, también lo ha hecho el financiamiento otorgado al sector privado. Este comportamiento refleja la estrecha relación existente entre la actividad económica y la expansión del crédito, ya que ambos indicadores tienden a evolucionar de manera conjunta en escenarios de crecimiento económico.
</p>

<p style="
font-size:15px;
color:#374151;
line-height:1.5;
text-align:justify;
">
No obstante, se observa un punto atípico correspondiente al segundo trimestre de 2020, período en el que la pandemia de COVID-19 provocó una fuerte contracción de la actividad económica. Las restricciones sanitarias, la disminución de la producción y los cambios en las políticas empresariales y financieras alteraron temporalmente la relación histórica entre ambas variables, generando una desviación respecto de la tendencia observada en el resto de la serie.
</p>

<p style="
font-size:15px;
color:#374151;
line-height:1.5;
text-align:justify;
">
En términos generales, la relación observada sugiere que el crecimiento del crédito y el desempeño del PIB se encuentran estrechamente vinculados. Por ello, las decisiones de política monetaria y financiera deben considerar el comportamiento conjunto de ambos indicadores, ya que cambios significativos en uno de ellos pueden influir en la dinámica del otro y, en consecuencia, en el desempeño de la economía nacional.
</p>
</div>

<!-- EXPORT: PREGUNTA_3 -->
<div style="
background:#ffffff;
padding:30px;
border:3px solid #cbd5e1;
border-radius:15px;
margin:20px 0;
">

<ol style="
font-size:25px;
color:#374151;
line-height:1.5;
padding-left:25px;
">
    
<b>¿Las remesas familiares presentan relación con el crecimiento de los medios de pago (M2)?</b>
</ol>

</div>

In [10]:
# Data Question 3
df_ques3 = df[["Trimestre","Año","medios de pagos totales", "remesas familiares"]]
df_ques3["Año"] = df_ques3["Año"].astype(str)
source = ColumnDataSource(df_ques3)
df_ques3.columns.name = None
TABLES["table_ques3"] = df_ques3
df_ques3

    Trimestre   Año  medios de pagos totales  remesas familiares
0           1  2015                 558854.6            10677.93
1           2  2015                 564714.4            11991.96
2           3  2015                 571462.5            12584.58
3           4  2015                 574962.5            12949.65
4           1  2016                 604368.3            12796.27
5           2  2016                 611167.3            14215.73
6           3  2016                 614850.4            13336.83
7           4  2016                 628914.3            14168.37
8           1  2017                 641288.3            14434.38
9           2  2017                 656254.7            15522.05
10          3  2017                 665484.7            14947.24
11          4  2017                 679206.0            15405.75
12          1  2018                 692491.8            14907.84
13          2  2018                 705501.6            17751.23
14          3  2018                 719265.9            18340.31
15          4  2018                 738983.6            19058.12
16          1  2019                 756806.4            17050.81
17          2  2019                 770431.5            20929.46
18          3  2019                 788696.5            21720.56
19          4  2019                 812983.6            21349.42
20          1  2020                 839986.0            18385.73
21          2  2020                 876841.8            19220.53
22          3  2020                 925433.6            24604.32
23          4  2020                 970135.8            25609.39
24          1  2021                1004037.2            24344.50
25          2  2021                1027504.0            29654.79
26          3  2021                1050036.7            31344.30
27          4  2021                1078804.9            33205.39
28          1  2022                1124387.4            30368.50
29          2  2022                1145884.8            36806.44
30          3  2022                1172161.9            35869.92
31          4  2022                1204517.8            37146.69
32          1  2023                1239764.0            34774.84
33          2  2023                1266321.2            40936.44
34          3  2023                1288164.6            40298.04
35          4  2023                1295463.2            39478.06
36          1  2024                1315673.2            36661.63
37          2  2024                1334439.4            43530.99
38          3  2024                1353332.8            43174.11
39          4  2024                1387724.9            43908.46
40          1  2025                1421946.5            43633.43
41          2  2025                1465146.9            49964.11
42          3  2025                1517531.7            52550.14
43          4  2025                1573084.1            50366.69

In [11]:
#Chart Question 3

p_ques3 = figure(
    height=550, 
    width=950,
    tools="pan,wheel_zoom,reset,save,tap",
    x_axis_label="remesas familiares",
    y_axis_label="M2",
    background_fill_color=theme["BACKGROUND"],
    border_fill_color=theme["PANEL"],
    title="Relación Remesas Familiares - Medios de Pago (M2)"
)

renderer = p_ques3.scatter(
    x="remesas familiares",
    y="medios de pagos totales",
    source=source,
    size=9,
    color=colors["M2"],
    alpha=0.8
)

hover = HoverTool(
    tooltips="""
    <div style="
        background:#0b0b0b;
        border:1px solid #d4af37;
        border-radius:6px;
        padding:8px;
        color:#fff;
    ">
        <div><b>Año:</b> @Año</div>
        <div><b>Trimestre:</b> @Trimestre</div>
        <div><b>M2:</b> @{medios de pagos totales}{0,0.00}</div>
        <div><b>Remesas:</b> @{remesas familiares}{0,0.00}</div>
    </div>
    """,
    renderers=[renderer]
)

p_ques3.add_tools(hover)

taptool = p_ques3.select(type=TapTool)
p_ques3.yaxis.formatter = NumeralTickFormatter(format="0.00a")
p_ques3.xaxis.formatter = NumeralTickFormatter(format="0.00a")
p_ques3.title.text_color = theme["ACCENT"] 
p_ques3.title.text_font_size = "20pt"        
p_ques3.title.align = "center"  
p_ques3.xaxis.axis_label_text_color = theme["TEXT"]
p_ques3.yaxis.axis_label_text_color = theme["TEXT"]
p_ques3.xaxis.major_label_text_color = theme["TEXT_SOFT"]
p_ques3.yaxis.major_label_text_color = theme["TEXT_SOFT"]
p_ques3.outline_line_color = theme["BORDER"]
p_ques3.xgrid.grid_line_color = theme["GRID"]
p_ques3.ygrid.grid_line_color = theme["GRID"]
p_ques3.xgrid.grid_line_alpha = theme["GRID_ALPHA"]
p_ques3.ygrid.grid_line_alpha = theme["GRID_ALPHA"]
p_ques3.toolbar.logo = None
p_ques3.toolbar.autohide = True

CHARTS["chart_ques3"] = p_ques3
show(p_ques3)

<!-- EXPORT: ANALISIS_3 -->
<div style="
background:#ffffff;
padding:25px;
border-left:6px solid #cbd5e1;
border-radius:10px;
margin:20px 0;
color:#e0e0e0;        
">

<p style="
font-size:15px;
color:#374151;
line-height:1.5;
text-align:justify;
">
Las remesas familiares y los medios de pago (M2) presentan una relación lineal positiva durante el período 2015–2025. A medida que el flujo de remesas aumenta, también se observa un crecimiento sostenido de los medios de pago, evidenciando una asociación entre ambas variables. Este comportamiento es consistente con el papel que desempeñan las remesas dentro de la economía guatemalteca, ya que una parte importante de estos recursos ingresa al sistema financiero y contribuye al incremento de la liquidez.
</p>

<p style="
font-size:15px;
color:#374151;
line-height:1.5;
text-align:justify;
">
A partir de 2019 se aprecia una ligera dispersión en la nube de puntos, generando un patrón tipo abanico. Este comportamiento coincide con el período en el que las remesas familiares mostraron una mayor volatilidad, principalmente durante los años de la pandemia y la posterior recuperación económica. No obstante, la tendencia general continúa siendo creciente, por lo que la asociación positiva entre ambas variables se mantiene.
</p>

<p style="
font-size:15px;
color:#374151;
line-height:1.5;
text-align:justify;
">
En términos de política económica, la relación observada sugiere que el seguimiento de las remesas familiares resulta relevante para evaluar la evolución de la liquidez del sistema financiero. Debido a que las remesas están expuestas a factores externos, como el desempeño económico de los países de origen de los migrantes y cambios en el contexto internacional, es recomendable que las autoridades monetarias y las instituciones financieras monitoreen su comportamiento como un indicador complementario para la toma de decisiones.
</p>
</div>

<!-- EXPORT: PREGUNTA_4 -->
<div style="
background:#ffffff;
padding:30px;
border:3px solid #cbd5e1;
border-radius:15px;
margin:20px 0;
">

<ol style="
font-size:25px;
color:#374151;
line-height:1.5;
padding-left:25px;
">
<b>¿Cómo evolucionó el spread bancario en moneda nacional y moneda extranjera?</b>
</ol>

</div>

In [12]:
# Data Qyestion 4

variable_ques4 = ["spread bancario en mn ", "spread bancario en me"]
df_ques4 = df[["Año", "Trimestre"] + variable_ques4]
df_ques4["Periodo"] = (df_ques4["Año"].astype(str) + "-T"+ df_ques4["Trimestre"].astype(str))
df_ques4["Fecha"] = pd.to_datetime(df_ques4["Año"].astype(str) + "-" + ((df_ques4["Trimestre"] - 1) * 3 + 1).astype(str) + "-01")

for col in variable_ques4:
    df[col] = (df[col].astype(str).str.replace("%", "", regex=False).astype(float)/ 100)
    
for col in variable_ques4: 
    df[col] = (df[col].astype(str).str.replace(",", "", regex=False).astype(float))

for var in variable_ques4: 
    df_ques4[var] = df[var] / df[var].iloc[0] * 100

source = ColumnDataSource(df_ques4)
df_ques4.columns.name = None
TABLES["table_ques4"] = df_ques4
df_ques4

,Año,Trimestre,spread bancario en mn,spread bancario en me,Periodo,Fecha
0,2015,1,100.000000,100.000000,2015-T1,2015-01-01
1,2015,2,98.879203,99.669967,2015-T2,2015-04-01
2,2015,3,97.509340,98.349835,2015-T3,2015-07-01
3,2015,4,96.513076,97.359736,2015-T4,2015-10-01
4,2016,1,94.520548,99.339934,2016-T1,2016-01-01
5,2016,2,94.769614,100.000000,2016-T2,2016-04-01
6,2016,3,95.267746,100.990099,2016-T3,2016-07-01
7,2016,4,95.516812,102.310231,2016-T4,2016-10-01
8,2017,1,94.769614,100.330033,2017-T1,2017-01-01
9,2017,2,95.018680,99.669967,2017-T2,2017-04-01
10,2017,3,95.143213,99.669967,2017-T3,2017-07-01
11,2017,4,95.267746,100.000000,2017-T4,2017-10-01
12,2018,1,96.886675,102.640264,2018-T1,2018-01-01
13,2018,2,96.762142,102.970297,2018-T2,2018-04-01
14,2018,3,96.637609,103.960396,2018-T3,2018-07-01
15,2018,4,96.513076,105.280528,2018-T4,2018-10-01
16,2019,1,96.264010,112.871287,2019-T1,2019-01-01
17,2019,2,96.513076,113.861386,2019-T2,2019-04-01
18,2019,3,96.139477,113.861386,2019-T3,2019-07-01
19,2019,4,95.641345,112.871287,2019-T4,2019-10-01
20,2020,1,97.260274,104.290429,2020-T1,2020-01-01
21,2020,2,97.758406,103.960396,2020-T2,2020-04-01
22,2020,3,98.132005,103.960396,2020-T3,2020-07-01
23,2020,4,98.754670,103.630363,2020-T4,2020-10-01
24,2021,1,100.124533,112.871287,2021-T1,2021-01-01
25,2021,2,100.249066,112.541254,2021-T2,2021-04-01
26,2021,3,100.373599,112.541254,2021-T3,2021-07-01
27,2021,4,100.498132,112.541254,2021-T4,2021-10-01
28,2022,1,99.501868,100.330033,2022-T1,2022-01-01
29,2022,2,99.750934,98.349835,2022-T2,2022-04-01
30,2022,3,100.124533,98.019802,2022-T3,2022-07-01
31,2022,4,100.373599,97.359736,2022-T4,2022-10-01
32,2023,1,98.256538,108.250825,2023-T1,2023-01-01
33,2023,2,98.007472,108.910891,2023-T2,2023-04-01
34,2023,3,97.758406,109.240924,2023-T3,2023-07-01
35,2023,4,97.509340,108.910891,2023-T4,2023-10-01
36,2024,1,94.022416,109.900990,2024-T1,2024-01-01
37,2024,2,93.275218,108.580858,2024-T2,2024-04-01
38,2024,3,92.652553,107.590759,2024-T3,2024-07-01
39,2024,4,92.278954,106.930693,2024-T4,2024-10-01
40,2025,1,94.645081,106.930693,2025-T1,2025-01-01
41,2025,2,95.143213,106.930693,2025-T2,2025-04-01
42,2025,3,95.392279,105.940594,2025-T3,2025-07-01
43,2025,4,95.641345,105.940594,2025-T4,2025-10-01

In [13]:
# Chart Question 4

p_ques4 = figure(
    width=950,
    height=450,
    x_axis_type="datetime",
    title="Evolución del spread bancario en MN y ME (Base 100)",
    background_fill_color=theme["BACKGROUND"],
    border_fill_color=theme["PANEL"],
    tools="pan,wheel_zoom,box_zoom,reset,save"
)
p_ques4.line(
    "Fecha",
    "spread bancario en mn ",
    source=source,
    color=colors["SPREAD_MN"],
    line_width=3,
    legend_label="Spread MN"
)

p_ques4.line(
    "Fecha",
    "spread bancario en me",
    source=source,
    color=colors["SPREAD_ME"],
    line_width=3,
    legend_label="Spread ME"
)


hover = HoverTool(
    tooltips="""
    <div style="
        background:#1f1720;
        border:1px solid #ff6b81;
        border-radius:8px;
        padding:8px;
        color:white;
    ">
        <b>Fecha:</b> @Periodo<br>
        <b>Valor:</b> $y{0.0}
    </div>
    """
)

p_ques4.add_tools(hover)
p_ques4.legend.location = "top_left"
p_ques4.legend.orientation = "vertical"
p_ques4.legend.background_fill_color = theme["PANEL"]
p_ques4.legend.background_fill_alpha = 0.9
p_ques4.legend.border_line_color = theme["BORDER"]
p_ques4.legend.label_text_color = theme["TEXT"]
p_ques4.legend.label_text_font_size = "10pt"
p_ques4.legend.padding = 8
p_ques4.legend.spacing = 6
p_ques4.legend.margin = 5
p_ques4.legend.click_policy = "hide"
p_ques4.yaxis.formatter = NumeralTickFormatter(format="0.00a")
p_ques4.toolbar.logo = None
p_ques4.toolbar.autohide = True
p_ques4.title.text_color = theme["ACCENT"] 
p_ques4.title.text_font_size = "20pt"        
p_ques4.title.align = "center"  
p_ques4.yaxis.axis_label = 'Saldos'
p_ques4.yaxis.axis_label_text_color = theme["TEXT"]
p_ques4.xaxis.major_label_text_color = theme["TEXT_SOFT"]
p_ques4.yaxis.major_label_text_color = theme["TEXT_SOFT"]
p_ques4.outline_line_color = theme["BORDER"]
p_ques4.xgrid.grid_line_color = theme["GRID"]
p_ques4.ygrid.grid_line_color = theme["GRID"]
p_ques4.xgrid.grid_line_alpha = theme["GRID_ALPHA"]
p_ques4.ygrid.grid_line_alpha = theme["GRID_ALPHA"]

select = figure(
    title="Seleccionar período",
    height=120,
    width=950,
    x_axis_type="datetime",
    y_axis_type=None,
    tools="",
    toolbar_location=None,
    background_fill_color=theme["BACKGROUND"],
    border_fill_color=theme["PANEL"]
)

select.line(
    "Fecha",
    "spread bancario en mn ",
    source=source,
    color=colors["SPREAD_MN"]
)
range_tool = RangeTool(x_range=p_ques4.x_range)
range_tool.overlay.fill_color = theme["ACCENT"]
range_tool.overlay.fill_alpha = 0.25
select.add_tools(range_tool)

CHARTS["chart_ques4"] = column(p_ques4)
show(column(p_ques4, select))

<!-- EXPORT: ANALISIS_4 -->
<div style="
background:#ffffff;
padding:25px;
border-left:6px solid #cbd5e1;
border-radius:10px;
margin:20px 0;
color:#e0e0e0;        
">

<p style="
font-size:15px;
color:#374151;
line-height:1.5;
text-align:justify;
">
La evolución del spread bancario en moneda nacional (MN) y moneda extranjera (ME) presenta diferencias importantes durante el período analizado. Tomando como referencia el primer trimestre de 2015 (índice base 100), el spread bancario en moneda nacional muestra una tendencia descendente y relativamente estable, con una variación aproximada entre 100.5 y 92.3. Por su parte, el spread bancario en moneda extranjera evidencia una mayor amplitud en sus fluctuaciones, alcanzando valores entre 113.9 y 97.4, lo que refleja una mayor variabilidad respecto a su período base.
</p>

<p style="
font-size:15px;
color:#374151;
line-height:1.5;
text-align:justify;
">
A partir de 2019 el spread bancario en moneda extranjera incrementa su volatilidad, comportamiento que comienza a moderarse hacia 2023. En contraste, el spread en moneda nacional mantiene un comportamiento más estable, aunque desde finales de 2021 inicia una reducción gradual que lo lleva a registrar su nivel mínimo durante el último trimestre de 2024. Estas variaciones coinciden temporalmente con un período de elevada incertidumbre económica internacional, caracterizado por los efectos de la pandemia de COVID-19 y posteriormente por el conflicto entre Rusia y Ucrania, eventos que influyeron sobre las condiciones financieras y los mercados internacionales.
</p>

<p style="
font-size:15px;
color:#374151;
line-height:1.5;
text-align:justify;
">
En conjunto, los resultados sugieren que el spread bancario en moneda nacional ha mantenido un comportamiento relativamente más estable que el observado en moneda extranjera. Esta diferencia puede interpretarse como un reflejo de la mayor sensibilidad de las operaciones denominadas en moneda extranjera frente a factores externos, mientras que el mercado en moneda nacional tiende a responder principalmente a las condiciones monetarias y financieras internas. Por ello, el seguimiento conjunto de ambos indicadores constituye una herramienta relevante para evaluar la estabilidad del sistema financiero y la evolución de las condiciones de financiamiento en el país.
</p>
</div>

<!-- EXPORT: PREGUMTA_5 -->
<div style="
background:#ffffff;
padding:30px;
border:3px solid #cbd5e1;
border-radius:15px;
margin:20px 0;
">

<ol style="
font-size:25px;
color:#374151;
line-height:1.5;
padding-left:25px;
">

<b>¿Qué indicador presentó el mayor crecimiento acumulado entre 2015 y 2025?</b>
</ol>

</div>

In [14]:
# Data Question 5

variables_ques5 = ["numerario en circulacion", "credito bancario total al sector privado", 
                   "medios de pagos totales", "remesas familiares", "PIB Trimestral"]
nombres = ["Numerario", "Crédito", "M2", "Remesas", "PIB"]
crecimiento = []

for var, nombre in zip(variables_ques5, nombres):
    porcentaje = ((df[var].iloc[-1] / df[var].iloc[0]) - 1) * 100
    crecimiento.append({"Indicador": nombre, "Crecimiento": porcentaje})

df_ques5 = (pd.DataFrame(crecimiento).sort_values("Crecimiento", ascending=False).reset_index(drop=True))
df_ques5["Crecimiento_txt"] = df_ques5["Crecimiento"].round(1).astype(str) + "%"
source = ColumnDataSource(df_ques5)
df_ques5.columns.name = None
TABLES["table_ques5"] = df_ques5
df_ques5

   Indicador  Crecimiento Crecimiento_txt
0    Remesas   371.689644          371.7%
1  Numerario   313.697400          313.7%
2         M2   181.483610          181.5%
3    Crédito   162.701621          162.7%
4        PIB   111.092196          111.1%

In [15]:
# Chart Question 5

p_ques5 = figure(
    y_range=list(df_ques5["Indicador"])[::-1],
    x_range=(0, 450), 
    height=400,
    width=800,
    title="Crecimiento acumulado de los indicadores (2015-2025)",
    background_fill_color=theme["BACKGROUND"],
    border_fill_color=theme["PANEL"],
    tools="pan,wheel_zoom,reset,save"
)

renderer = p_ques5.hbar(
    y="Indicador",
    right="Crecimiento",
    height=0.75,
    source=source,
    color=theme["ACCENT"]
)

labels = LabelSet(
    x="Crecimiento",       
    y="Indicador",         
    text="Crecimiento_txt", 
    level="glyph",
    x_offset=10,           
    y_offset=0,             
    source=source,
    text_font_size="10pt",
    text_color=theme["TEXT"]
)

hover = HoverTool(
    tooltips="""
    <div style="
        background:#ffffff;
        border:1px solid #ff6b81;
        border-radius:8px;
        padding:8px;
        color:#374151;
    ">
        <div><b>Indicador:</b> @Indicador</div>
        <div><b>Crecimiento:</b> @Crecimiento{0.0}%</div>
    </div>
    """,
    renderers=[renderer]
)

p_ques5.add_layout(labels)
p_ques5.add_tools(hover)
p_ques5.xaxis.major_label_orientation = 1.0  
p_ques5.title.text_color = theme["ACCENT"] 
p_ques5.title.text_font_size = "20pt"        
p_ques5.title.align = "center"  
p_ques5.xaxis.axis_label_text_color = theme["TEXT"]
p_ques5.yaxis.axis_label_text_color = theme["TEXT"]
p_ques5.xaxis.major_label_text_color = theme["TEXT_SOFT"]
p_ques5.yaxis.major_label_text_color = theme["TEXT_SOFT"]
p_ques5.outline_line_color = theme["BORDER"]
p_ques5.xgrid.grid_line_color = theme["GRID"]
p_ques5.ygrid.grid_line_color = theme["GRID"]
p_ques5.xgrid.grid_line_alpha = theme["GRID_ALPHA"]
p_ques5.ygrid.grid_line_alpha = theme["GRID_ALPHA"]
p_ques5.toolbar.logo = None
p_ques5.toolbar.autohide = True

CHARTS["chart_ques5"] = p_ques5
show(p_ques5)

<!-- EXPORT: ANALISIS_5 -->
<div style="
background:#ffffff;
padding:25px;
border-left:6px solid #cbd5e1;
border-radius:10px;
margin:20px 0;
color:#e0e0e0;        
">

<p style="
font-size:15px;
color:#374151;
line-height:1.5;
text-align:justify;
">
El crecimiento acumulado de los principales indicadores monetarios y financieros durante el período 2015–2025 evidencia que las remesas familiares fueron la variable con mayor expansión, registrando un incremento aproximado del <b>371.7%</b> respecto al período base. En segundo lugar se ubicó el numerario en circulación con un crecimiento cercano al <b>313.7%</b>, mientras que los medios de pago (M2), el crédito bancario al sector privado y el Producto Interno Bruto (PIB) mostraron incrementos más moderados, comprendidos entre el <b>111.1%</b> y el <b>181.5%</b>.
</p>

<p style="
font-size:15px;
color:#374151;
line-height:1.5;
text-align:justify;
">
Estos resultados reflejan que, durante la última década, las remesas familiares se consolidaron como uno de los principales motores del crecimiento económico y de la expansión de la liquidez en Guatemala. Asimismo, el importante aumento del numerario en circulación sugiere que el efectivo continúa desempeñando un papel predominante dentro de las transacciones económicas del país, situación que puede estar asociada con una elevada utilización del dinero en efectivo y con los desafíos que aún existen en materia de inclusión financiera.
</p>

<p style="
font-size:15px;
color:#374151;
line-height:1.5;
text-align:justify;
">
En conjunto, el comportamiento de estos indicadores muestra que el crecimiento del sistema monetario no ha sido homogéneo entre todas las variables. Mientras el PIB y el crédito bancario mantuvieron una evolución más estable y consistente con el crecimiento económico de largo plazo, las remesas familiares y el numerario fueron los componentes que registraron la mayor dinámica de expansión, resaltando su importancia dentro de la economía guatemalteca y su potencial influencia sobre la liquidez y el consumo interno.
</p>

</div>

<!-- EXPORT: PREGUMTA_6 -->
<div style="
background:#ffffff;
padding:30px;
border:3px solid #cbd5e1;
border-radius:15px;
margin:20px 0;
">

<ol style="
font-size:25px;
color:#374151;
line-height:1.5;
padding-left:25px;
">
    
<b>¿Cuál ha sido la variación trimestral del PIB?</b>
</ol>

</div>

In [16]:
# Data Question 6

df_ques6 = df[["Año", "Trimestre", "PIB Trimestral"]].copy()
df_ques6["Fecha"] = pd.to_datetime(df_ques6["Año"].astype(str) + "-" + ((df_ques6["Trimestre"] - 1) * 3 + 1).astype(str) + "-01")
df_ques6["Variación %"] = (df_ques6["PIB Trimestral"].pct_change() * 100)
df_ques6["Color"] = np.where(df_ques6["Variación %"] >= 0, theme["POSITIVE"], theme["NEGATIVE"])
df_ques6 = df_ques6.dropna().reset_index(drop=True)
source = ColumnDataSource(df_ques6)
df_ques6.columns.name = None
TABLES["table_ques6"] = df_ques6
df_ques6

     Año  Trimestre  PIB Trimestral      Fecha  Variación %    Color
0   2015          2        116183.4 2015-04-01    -1.453723  #dc2626
1   2015          3        118716.5 2015-07-01     2.180260  #22c55e
2   2015          4        123225.6 2015-10-01     3.798208  #22c55e
3   2016          1        123838.5 2016-01-01     0.497380  #22c55e
4   2016          2        122799.4 2016-04-01    -0.839077  #dc2626
5   2016          3        124518.0 2016-07-01     1.399518  #22c55e
6   2016          4        130845.7 2016-10-01     5.081755  #22c55e
7   2017          1        131682.7 2017-01-01     0.639685  #22c55e
8   2017          2        127650.4 2017-04-01    -3.062133  #dc2626
9   2017          3        130291.7 2017-07-01     2.069167  #22c55e
10  2017          4        136882.6 2017-10-01     5.058572  #22c55e
11  2018          1        136945.1 2018-01-01     0.045660  #22c55e
12  2018          2        134587.6 2018-04-01    -1.721493  #dc2626
13  2018          3        136449.4 2018-07-01     1.383337  #22c55e
14  2018          4        143385.9 2018-10-01     5.083569  #22c55e
15  2019          1        144940.7 2019-01-01     1.084347  #22c55e
16  2019          2        145359.2 2019-04-01     0.288739  #22c55e
17  2019          3        147623.6 2019-07-01     1.557796  #22c55e
18  2019          4        156048.5 2019-10-01     5.707014  #22c55e
19  2020          1        151214.2 2020-01-01    -3.097947  #dc2626
20  2020          2        136507.7 2020-04-01    -9.725608  #dc2626
21  2020          3        150128.8 2020-07-01     9.978265  #22c55e
22  2020          4        162271.8 2020-10-01     8.088388  #22c55e
23  2021          1        162670.4 2021-01-01     0.245637  #22c55e
24  2021          2        161775.5 2021-04-01    -0.550131  #dc2626
25  2021          3        167039.9 2021-07-01     3.254139  #22c55e
26  2021          4        177193.0 2021-10-01     6.078248  #22c55e
27  2022          1        179171.0 2022-01-01     1.116297  #22c55e
28  2022          2        179610.5 2022-04-01     0.245296  #22c55e
29  2022          3        185624.2 2022-07-01     3.348190  #22c55e
30  2022          4        196401.9 2022-10-01     5.806193  #22c55e
31  2023          1        200405.8 2023-01-01     2.038626  #22c55e
32  2023          2        200133.3 2023-04-01    -0.135974  #dc2626
33  2023          3        203402.0 2023-07-01     1.633261  #22c55e
34  2023          4        212918.7 2023-10-01     4.678764  #22c55e
35  2024          1        214009.8 2024-01-01     0.512449  #22c55e
36  2024          2        213837.1 2024-04-01    -0.080697  #dc2626
37  2024          3        219785.4 2024-07-01     2.781697  #22c55e
38  2024          4        230755.2 2024-10-01     4.991141  #22c55e
39  2025          1        230802.6 2025-01-01     0.020541  #22c55e
40  2025          2        231747.8 2025-04-01     0.409527  #22c55e
41  2025          3        235583.1 2025-07-01     1.654946  #22c55e
42  2025          4        248872.0 2025-10-01     5.640855  #22c55e

In [17]:
# Chart Question 6

p_ques6 = figure(
    width=900,
    height=420,
    x_axis_type="datetime",
    title="Variación trimestral del PIB",
    tools="pan,wheel_zoom,box_zoom,reset,save",
    background_fill_color=theme["BACKGROUND"],
    border_fill_color=theme["PANEL"]
)

renderer = p_ques6.vbar(
    x="Fecha",
    top="Variación %",
    width=70*24*60*60*1000,     
    source=source,
    fill_color="Color",
    line_color="Color"
)

# Línea en cero
p_ques6.add_layout(
    Span(
        location=0,
        dimension="width",
        line_color=theme["TEXT_SOFT"],
        line_dash="dashed",
        line_width=2
    )
)

hover = HoverTool(
    renderers=[renderer],
    tooltips="""
    <div style="
        background:#1f1720;
        border:1px solid #ff6b81;
        border-radius:8px;
        padding:8px;
        color:white;
    ">
        <b>Año:</b> @Año<br>
        <b>Trimestre:</b> @Trimestre<br>
        <b>Variación:</b> @{Variación %}{0.00}%<br>
        <b>PIB:</b> @{PIB Trimestral}{0,0.00}
    </div>
    """
)
p_ques6.yaxis.axis_label = "Variación (%)"
p_ques6.yaxis.formatter = NumeralTickFormatter(format="0.0")
p_ques6.yaxis.major_label_overrides = {}
p_ques6.add_layout(labels)
p_ques6.add_tools(hover)
p_ques6.xaxis.major_label_orientation = 1.0  
p_ques6.title.text_color = theme["ACCENT"] 
p_ques6.title.text_font_size = "20pt"        
p_ques6.title.align = "center"  
p_ques6.xaxis.axis_label_text_color = theme["TEXT"]
p_ques6.yaxis.axis_label_text_color = theme["TEXT"]
p_ques6.xaxis.major_label_text_color = theme["TEXT_SOFT"]
p_ques6.yaxis.major_label_text_color = theme["TEXT_SOFT"]
p_ques6.outline_line_color = theme["BORDER"]
p_ques6.xgrid.grid_line_color = theme["GRID"]
p_ques6.ygrid.grid_line_color = theme["GRID"]
p_ques6.xgrid.grid_line_alpha = theme["GRID_ALPHA"]
p_ques6.ygrid.grid_line_alpha = theme["GRID_ALPHA"]
p_ques6.toolbar.logo = None
p_ques6.toolbar.autohide = True

CHARTS["chart_ques6"] = p_ques6
show(p_ques6)

<!-- EXPORT: ANALISIS_6 -->
<div style="
background:#ffffff;
padding:25px;
border-left:6px solid #cbd5e1;
border-radius:10px;
margin:20px 0;
color:#e0e0e0;        
">

<p style="
font-size:15px;
color:#374151;
line-height:1.5;
text-align:justify;
">
La variación trimestral del Producto Interno Bruto (PIB) muestra un comportamiento claramente diferenciado antes y después del año 2020. Durante el período comprendido entre 2015 y 2019 se observa un patrón estacional relativamente estable, caracterizado por un crecimiento importante en el cuarto trimestre de cada año y una desaceleración o variación negativa en el segundo trimestre en la mayoría de los períodos analizados. Este comportamiento refleja la existencia de ciclos económicos recurrentes asociados a la dinámica productiva nacional.
</p>

<p style="
font-size:15px;
color:#374151;
line-height:1.5;
text-align:justify;
">
El año 2020 representa un punto de quiebre en la serie histórica debido a la crisis provocada por la pandemia de COVID-19. Como consecuencia de las restricciones sanitarias y la paralización parcial de las actividades económicas, el PIB registró una contracción significativa durante los dos primeros trimestres, alcanzando una variación mínima cercana al -9.73%. Posteriormente, la reapertura gradual de la economía permitió una rápida recuperación de la actividad productiva, reflejada en una variación positiva cercana al 9.98% durante el tercer trimestre, constituyendo el mayor crecimiento observado en todo el período de estudio.
</p>

<p style="
font-size:15px;
color:#374151;
line-height:1.5;
text-align:justify;
">
A partir de 2022 la economía guatemalteca retomó un comportamiento más estable, registrando tasas de crecimiento moderadas y sin variaciones trimestrales negativas significativas. Asimismo, vuelve a apreciarse el patrón estacional observado antes de la pandemia, lo que sugiere un proceso de normalización de la actividad económica tras el choque extraordinario experimentado en 2020. En conjunto, estos resultados evidencian la resiliencia de la economía guatemalteca y su capacidad para recuperar la senda de crecimiento una vez superado el período de mayor incertidumbre.
</p>

</div>

<div style="
background:#ffffff;
padding:30px;
border:3px solid #cbd5e1;
border-radius:15px;
margin:20px 0;
">

<ol style="
font-size:25px;
color:#374151;
line-height:1.5;
padding-left:25px;
">
<!-- EXPORT: PREGUMTA_7 -->
    
<b>¿Existe una relación entre el crecimiento de las remesas y el PIB?</b>
</ol>

</div>

In [18]:
# Data Question 7

df_ques7 = df[["Trimestre", "Año", "remesas familiares", "PIB Trimestral"]]
df_ques7["Año"] = df_ques7["Año"].astype(str)
source = ColumnDataSource(df_ques7)
df_ques7.columns.name = None
TABLES["table_ques7"] = df_ques7
df_ques7

    Trimestre   Año  remesas familiares  PIB Trimestral
0           1  2015            10677.93        117897.3
1           2  2015            11991.96        116183.4
2           3  2015            12584.58        118716.5
3           4  2015            12949.65        123225.6
4           1  2016            12796.27        123838.5
5           2  2016            14215.73        122799.4
6           3  2016            13336.83        124518.0
7           4  2016            14168.37        130845.7
8           1  2017            14434.38        131682.7
9           2  2017            15522.05        127650.4
10          3  2017            14947.24        130291.7
11          4  2017            15405.75        136882.6
12          1  2018            14907.84        136945.1
13          2  2018            17751.23        134587.6
14          3  2018            18340.31        136449.4
15          4  2018            19058.12        143385.9
16          1  2019            17050.81        144940.7
17          2  2019            20929.46        145359.2
18          3  2019            21720.56        147623.6
19          4  2019            21349.42        156048.5
20          1  2020            18385.73        151214.2
21          2  2020            19220.53        136507.7
22          3  2020            24604.32        150128.8
23          4  2020            25609.39        162271.8
24          1  2021            24344.50        162670.4
25          2  2021            29654.79        161775.5
26          3  2021            31344.30        167039.9
27          4  2021            33205.39        177193.0
28          1  2022            30368.50        179171.0
29          2  2022            36806.44        179610.5
30          3  2022            35869.92        185624.2
31          4  2022            37146.69        196401.9
32          1  2023            34774.84        200405.8
33          2  2023            40936.44        200133.3
34          3  2023            40298.04        203402.0
35          4  2023            39478.06        212918.7
36          1  2024            36661.63        214009.8
37          2  2024            43530.99        213837.1
38          3  2024            43174.11        219785.4
39          4  2024            43908.46        230755.2
40          1  2025            43633.43        230802.6
41          2  2025            49964.11        231747.8
42          3  2025            52550.14        235583.1
43          4  2025            50366.69        248872.0

In [19]:
# Chart Question 7

p_ques7 = figure(
    height=550, 
    width=950,
    tools="pan,wheel_zoom,reset,save,tap",
    x_axis_label="Remesas familiares",
    y_axis_label="PIB",
    background_fill_color=theme["BACKGROUND"],
    border_fill_color=theme["PANEL"],
    title="Relación Remesas familiares - PIB"
)

renderer = p_ques7.scatter(
    x="remesas familiares",
    y="PIB Trimestral",
    source=source,
    size=9,
    color=colors["REMESAS"],  
    alpha=0.8
)

hover = HoverTool(
    tooltips="""
    <div style="
        background:#0b0b0b;
        border:1px solid #d4af37;
        border-radius:6px;
        padding:8px;
        color:#fff;
    ">
        <div><b>Año:</b> @Año</div>
        <div><b>Trimestre:</b> @Trimestre</div>
        <div><b>Remesas familiares:</b> @{remesas familiares}{0,0.00}</div>
        <div><b>PIB:</b> @{PIB Trimestral}{0,0.00}</div>
    </div>
    """,
    renderers=[renderer]
)

p_ques7.add_tools(hover)


taptool = p_ques7.select(type=TapTool)

p_ques7.yaxis.formatter = NumeralTickFormatter(format="0.00a")
p_ques7.xaxis.formatter = NumeralTickFormatter(format="0.00a")
p_ques7.title.text_color = theme["ACCENT"] 
p_ques7.title.text_font_size = "20pt"        
p_ques7.title.align = "center"  
p_ques7.xaxis.axis_label_text_color = theme["TEXT"]
p_ques7.yaxis.axis_label_text_color = theme["TEXT"]
p_ques7.xaxis.major_label_text_color = theme["TEXT_SOFT"]
p_ques7.yaxis.major_label_text_color = theme["TEXT_SOFT"]
p_ques7.outline_line_color = theme["BORDER"]
p_ques7.xgrid.grid_line_color = theme["GRID"]
p_ques7.ygrid.grid_line_color = theme["GRID"]
p_ques7.xgrid.grid_line_alpha = theme["GRID_ALPHA"]
p_ques7.ygrid.grid_line_alpha = theme["GRID_ALPHA"]
p_ques7.toolbar.logo = None
p_ques7.toolbar.autohide = True

CHARTS["chart_ques7"] = p_ques7
show(p_ques7)

<!-- EXPORT: ANALISIS_7 -->
<div style="
background:#ffffff;
padding:25px;
border-left:6px solid #cbd5e1;
border-radius:10px;
margin:20px 0;
color:#e0e0e0;        
">

<p style="
font-size:15px;
color:#374151;
line-height:1.5;
text-align:justify;
">
El comportamiento observado evidencia que el crecimiento de las remesas familiares ha estado acompañado por una expansión del Producto Interno Bruto (PIB) durante el período 2015–2025. A medida que aumenta el ingreso de divisas provenientes del exterior, también se incrementa la capacidad de consumo e inversión de los hogares receptores, lo que contribuye al dinamismo de distintos sectores de la economía y favorece el crecimiento de la producción nacional.
</p>

<p style="
font-size:15px;
color:#374151;
line-height:1.5;
text-align:justify;
">
Aunque a partir de 2019 la dispersión de los datos es ligeramente mayor, principalmente por los efectos económicos derivados de la pandemia de COVID-19, la trayectoria general continúa mostrando un comportamiento creciente. Esto indica que, aun bajo escenarios de incertidumbre, las remesas mantuvieron un papel importante como fuente de ingresos para los hogares guatemaltecos y como mecanismo de apoyo para la recuperación de la actividad económica.</p>

<p style="
font-size:15px;
color:#374151;
line-height:1.5;
text-align:justify;
">
Desde una perspectiva macroeconómica, estos resultados resaltan la relevancia de las remesas dentro del modelo económico guatemalteco. Sin embargo, también evidencian una dependencia significativa de recursos provenientes del exterior, los cuales pueden verse afectados por cambios en las condiciones económicas internacionales, el mercado laboral de los países donde residen los migrantes o modificaciones en las políticas migratorias. Por ello, resulta conveniente que las autoridades económicas complementen este flujo de ingresos con políticas orientadas a fortalecer la inversión, la productividad y la generación de empleo interno, reduciendo gradualmente la dependencia de factores externos como fuente de crecimiento económico.
</p>
</div>

<div style="
background:#ffffff;
padding:35px;
border:3px solid #cbd5e1;
border-radius:15px;
margin:20px 0;
">

<h1 style="
font-size:35px;
color:#ef4444;
text-align:center;
margin-top:0;
margin-bottom:10px;
">
Conclusiones y Recomendaciones
</h1>

<hr style="border:5px solid #cbd5e1; margin-bottom:30px;">

</div>

<div style="
background:#ffffff;
padding:35px;
border:3px solid #cbd5e1;
border-radius:15px;
margin:20px 0;
">

<h3 style="
font-size:35px;
color:#ef4444;
margin-bottom:10px;
">
Conclusiones
</h3>

<!-- EXPORT: CONCLUSIONES -->
<div style="
background:#ffffff;
padding:35px;
border:3px solid #cbd5e1;
border-radius:15px;
margin:20px 0;
">

<ul style="
font-size:17px;
color:#374151;
line-height:1.8;
text-align:justify;
">

<li>Durante el período 2015–2025, la economía guatemalteca mostró una tendencia de crecimiento sostenido en la mayoría de los indicadores monetarios y financieros analizados, siendo las remesas familiares y el numerario en circulación las variables que registraron el mayor crecimiento acumulado.</li>

<li>Los análisis realizados evidencian una asociación positiva entre el Producto Interno Bruto (PIB) y variables como el crédito bancario, los medios de pago (M2) y las remesas familiares, lo que refleja la estrecha relación existente entre la actividad económica, la liquidez y el financiamiento del sector privado.</li>

<li>El spread bancario en moneda nacional presentó un comportamiento más estable que el spread en moneda extranjera, lo cual sugiere que el mercado financiero interno ofrece menores fluctuaciones frente a los cambios originados por factores externos.</li>

<li>Las remesas familiares constituyen uno de los principales motores de la liquidez y del crecimiento económico del país. Sin embargo, su elevada participación también evidencia una importante dependencia de ingresos provenientes del exterior, situación que representa un riesgo ante posibles cambios en el entorno económico internacional.</li>

<li>La evolución del PIB permitió identificar un patrón estacional relativamente estable que únicamente fue interrumpido durante la pandemia de COVID-19, período en el que la economía experimentó una fuerte contracción seguida por un proceso gradual de recuperación y normalización.</li>

</ul>

</div>

<div style="
background:#ffffff;
padding:35px;
border:3px solid #cbd5e1;
border-radius:15px;
margin:20px 0;
">

<h3 style="
font-size:35px;
color:#ef4444;
margin-top:35px;
margin-bottom:10px;
">
Recomendaciones
</h3>

<!-- EXPORT: RECOMEMDACIONES -->
<div style="
background:#ffffff;
padding:35px;
border:3px solid #cbd5e1;
border-radius:15px;
margin:20px 0;
">

<ul style="
font-size:17px;
color:#374151;
line-height:1.8;
text-align:justify;
">

<li>Las instituciones financieras y los organismos encargados de la política económica deberían mantener un monitoreo permanente de indicadores como las remesas familiares, el numerario en circulación y los medios de pago, debido a su estrecha relación con la evolución de la actividad económica nacional.</li>

<li>Para estudios orientados a la formulación de políticas públicas o decisiones estratégicas, se recomienda complementar este análisis descriptivo con modelos econométricos que permitan cuantificar el impacto y la causalidad entre las variables analizadas.</li>

<li>Es recomendable utilizar información estadística actualizada y revisar periódicamente las series publicadas por el Banco de Guatemala, ya que las cifras más recientes pueden ser objeto de revisiones o ajustes metodológicos.</li>

<li>Finalmente, resulta conveniente impulsar políticas que fortalezcan la inclusión financiera y promuevan una mayor bancarización, con el propósito de reducir la dependencia del efectivo y canalizar una mayor proporción de los recursos provenientes de remesas hacia el sistema financiero formal.</li>

</ul>

</div>

<div style="
background:#ffffff;
padding:35px;
border:3px solid #cbd5e1;
border-radius:15px;
margin:20px 0;
">

<h1 style="
font-size:55px;
color:#ef4444;
text-align:center;
margin-top:0;
margin-bottom:10px;
">
Exportar Proyecto
</h1>

<hr style="border:5px solid #ef4444; margin-bottom:30px;">

</div>

In [20]:
#Export Tables

export_tables.exportar_tablas(TABLES)

-> Tabla 'table.tex' exportada con éxito en la carpeta '../tables/'.
-> Tabla 'table_ques1.tex' exportada con éxito en la carpeta '../tables/'.
-> Tabla 'table_ques2.tex' exportada con éxito en la carpeta '../tables/'.
-> Tabla 'table_ques3.tex' exportada con éxito en la carpeta '../tables/'.
-> Tabla 'table_ques4.tex' exportada con éxito en la carpeta '../tables/'.
-> Tabla 'table_ques5.tex' exportada con éxito en la carpeta '../tables/'.
-> Tabla 'table_ques6.tex' exportada con éxito en la carpeta '../tables/'.
-> Tabla 'table_ques7.tex' exportada con éxito en la carpeta '../tables/'.
Todas las tablas fueron exportadas correctamente.

In [21]:
#Export Charts

export_charts.exportar_graficas(CHARTS)

-> chart_ques1.png exportada

-> chart_ques2.png exportada

-> chart_ques3.png exportada

-> chart_ques4.png exportada

-> chart_ques5.png exportada

-> chart_ques6.png exportada

-> chart_ques7.png exportada

Todas las gráficas fueron exportadas correctamente.

In [22]:
#Export Text

export_text.exportar_reporte_textos("caso 3.ipynb")

-> 'titulo.tex' guardado en '../text/'
-> 'contexto.tex' guardado en '../text/'
-> 'objetivo.tex' guardado en '../text/'
-> 'pregunta_1.tex' guardado en '../text/'

-> 'analisis_1.tex' guardado en '../text/'
-> 'pregunta_2.tex' guardado en '../text/'
-> 'analisis_2.tex' guardado en '../text/'
-> 'pregunta_3.tex' guardado en '../text/'
-> 'analisis_3.tex' guardado en '../text/'
-> 'pregunta_4.tex' guardado en '../text/'
-> 'analisis_4.tex' guardado en '../text/'
-> 'pregumta_5.tex' guardado en '../text/'
-> 'analisis_5.tex' guardado en '../text/'
-> 'pregumta_6.tex' guardado en '../text/'
-> 'analisis_6.tex' guardado en '../text/'
-> 'pregumta_7.tex' guardado en '../text/'
-> 'analisis_7.tex' guardado en '../text/'
-> 'conclusiones.tex' guardado en '../text/'
-> 'recomemdaciones.tex' guardado en '../text/'
Textos exportados correctamente.